sudo: required
services:
  - docker

before_install:
  - docker build -t catchkathirk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run catchkathirk/react-test npm test -- --coverage

after_success:
  - docker build -t catchkathirk/multi-client ./client
  - docker build -t catchkathirk/multi-nginx ./nginx
  - docker build -t catchkathirk/multi-server ./server
  - docker build -t catchkathirk/multi-worker ./worker
#  Login to Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# Push build images to docker hub
  - docker push catchkathirk/multi-client
  - docker push catchkathirk/multi-nginx
  - docker push catchkathirk/multi-client
  - docker push catchkathirk/multi-client